### PR TITLE
Introduce -tune command line option to set env vars and mca params from file

### PR DESCRIPTION
**Pull request by elenash**
This commit brings new mca parameter -mca mca_base_envar_file_prefix and command line option -tune to specify a single file or list of them separated by ":" to set mca parameters and environment variables with the following syntax:
    - every line can hold zero or many "-x" or "-mca" args with single or double dash
    - support patterns: -mca var val  -mca var "val"  -x var=val  -x var  (mca params can be in quotes, env vars only without quotes)
    - ignore spaces (no matter how many extra spaces or tabs are in the line)
    - support old (var=val) and new syntax in different lines
    - if arg is duplicated, its latest value is stored.

Examples:
1) cat app.conf
  -x b=2 -x a=3 

cmd:  -x a=1 -tune app.conf                                                                -> a=1 b=2

2) cat app.conf
 -mca btl ^tcp

  cmd:  -tune app.conf                                                                       -> -mca btl ^tcp

3) cat app.conf
 --mca btl ^tcp

cmd:  --mca btl tcp,self -tune app.conf                                              -> --mca btl tcp,self      

4) cat app.conf
 -mca btl ^tcp

cat mca.conf
 btl=^openib

cmd:  -mca btl tcp,self   -tune app.conf   -am mca.conf                         -> -mca btl tcp,self

5) cat app.conf
 -mca btl ^tcp

cat mca.conf
 btl=^openib

  cmd:  -tune app.conf   -am mca.conf                                                 -> -mca btl ^tcp

6) export e=5
cat app.conf
-x a=1 -x b=2 -x c=3

cat app2.conf
-x d=4 -x e -x c=8
cmd:   –tune app1.conf,app2.conf                                                      -> a=1 b=2 c=8 d=4 e=5

A conf file can be specified with absolute path, relative path or just name, there exist mca variables to specify path to look in as for -am option. 

Currently this feature works properly only when job is launched under mpirun, direct launch is supported limitedly: new env vars are set in the environment after application start (on MPI_Init), so it doesn't work for non-MPI applications.

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1494 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_77/output/errors/index.html

* Coverity found 30 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/oshmem_77/output/errors/index.html

* Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/fca_77/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by elenash** [comment]
@miked-mellanox What do you mean in your question about separator?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/77/
Test PASSed.

**Comment by bureddy** [comment]
"if arg is duplicated, its latest value is stored." ==> Do you mean first occurrence of the variable in the command line? From your examples, this looks like the case.  Isn't this conflicting with existing mpirun order rules?

currently, mpirun takes last specified value if it is duplicate

for example in command " mpirun  -np 2 -map-by node  -map-by core" , it considers as "-map-by core"

**Comment by elenash** [comment]
@bureddy I mean if conf file contains multiple occurrences of the same mca parameter or env variable, value of the last one will be taken.
-x a=1 -x b=2 -x a=3     -> a=3 b=2

**Comment by mellanox-github** [comment]
* Coverity found 1494 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_78/output/errors/index.html

* Coverity found 30 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/oshmem_78/output/errors/index.html

* Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/fca_78/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/78/
Test PASSed.

**Comment by mellanox-github** [comment]
* Coverity found 1494 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_79/output/errors/index.html

* Coverity found 30 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/oshmem_79/output/errors/index.html

* Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/fca_79/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/79/
Test PASSed.

**Comment by bureddy** [comment]
@elenash , I was referring to order between conf file param, and non-conf file param, in your example

1) cat app.conf
-x b=2 -x a=3
cmd: -x a=1 -tune app.conf -> a=1 b=2

The above one not same(equal to) either
  1) -x a=1 -x b=2 -x a=3  
      or
   2)  cat app.conf
          -x a=1 -x b=2 -x a=3 

it is fine If this is expected behavior, Just wondering, if conf file params always override by command line option irrespective of -tune option location in the command line.

**Comment by elenash** [comment]
@bureddy The location of -tune option in the command line doesn't determine anything. Sorry for confusing you.
The priorities are the following:
1. If cmd line contains only -x arg, then the latest value from the line is taken
2. If cmd line doesn't contain -x but contains -tune, and conf file contains -x inside, then the latest value (the lowest) from the file is taken.
3. If cmd line contains both -x and -tune, and conf file contains -x also, and there are duplicates in file and in command line, then the value from command line is taken but value from conf file is ignored.

**Pull request merged**
