### PR TITLE
OSHMEM/ikrit: fix valgrind error

### PR DESCRIPTION
**Pull request by igor-ivanov**
@miked-mellanox could you look

related ompi-release commit
https://github.com/open-mpi/ompi-release/commit/b0bedf6f5c94a6157ae3380968e58690040aa22a

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//175/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/175/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//176/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/176/ for details. (Mellanox internal link)

**Pull request merged**
