### PR TITLE
HCOLL: enable by defaut

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by bureddy** [comment]
update PR with default enabled option scoll_mpi_enable

**Comment by mellanox-github** [comment]
* Coverity found 1418 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_106/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
* Coverity found 1418 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_107/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/106/

**Build Log**
*last 50 lines*

 ```
[...truncated 141952 lines...]
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o overlap.o overlap.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o overlap overlap.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o no_overlap.o no_overlap.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o no_overlap no_overlap.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred.o conc_allred.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o conc_allred conc_allred.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred_th.o conc_allred_th.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o conc_allred_th conc_allred_th.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o collcomp.o collcomp.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o collcomp collcomp.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate.o message_rate.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o message_rate message_rate.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate_th.o message_rate_th.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o message_rate_th message_rate_th.o
+ popd
/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace
+ '[' no == no ']'
+ btl_tcp=no
+ btl_vader=no
+ btl_openib=no
+ for exe in overlap latency
+ exe_path=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ PATH=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin:/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ LD_LIBRARY_PATH=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/lib:
+ mpi_runner 4 /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
+ local np=4
+ local exe_path=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ local exe_args=8
+ local 'common_mca=-bind-to core'
+ local 'mca=-bind-to core'
+ '[' no == yes ']'
+ '[' yes == yes ']'
+ timeout -s SIGKILL 10m mpirun -np 4 -bind-to core -mca pml ob1 -mca btl self,sm /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
Time per iteration on each process (ms)
Time 	 Compute time 	 Comm time
./jenkins_scripts/jenkins/ompi/ompi_jenkins.sh: line 144: 31811 Killed                  $timeout_exe mpirun -np $np $mca -mca pml ob1 -mca btl self,sm ${exe_path} ${exe_args}
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/106/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/106/tap-master-files/cov_stat.tap].
TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_106/output/errors/index.html
Setting commit status on GitHub for https://api.github.com/repos/mellanox-hpc/ompi-release/commit/3c798d0f363a5fcf6b07feec02df5788b972a3eb
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 4f144e53457a4fa8ac72ba3ed28c5028b31d04a5 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/106/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/107/

**Build Log**
*last 50 lines*

 ```
[...truncated 141952 lines...]
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -O   -c -o overlap.o overlap.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -o overlap overlap.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -O   -c -o no_overlap.o no_overlap.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -o no_overlap no_overlap.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -O   -c -o conc_allred.o conc_allred.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -o conc_allred conc_allred.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -O   -c -o conc_allred_th.o conc_allred_th.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -o conc_allred_th conc_allred_th.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -O   -c -o collcomp.o collcomp.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -o collcomp collcomp.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -O   -c -o message_rate.o message_rate.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -o message_rate message_rate.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -O   -c -o message_rate_th.o message_rate_th.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -o message_rate_th message_rate_th.o
+ popd
/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2
+ '[' no == no ']'
+ btl_tcp=no
+ btl_vader=no
+ btl_openib=no
+ for exe in overlap latency
+ exe_path=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ PATH=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin:/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ LD_LIBRARY_PATH=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/lib:
+ mpi_runner 4 /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
+ local np=4
+ local exe_path=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ local exe_args=8
+ local 'common_mca=-bind-to core'
+ local 'mca=-bind-to core'
+ '[' no == yes ']'
+ '[' yes == yes ']'
+ timeout -s SIGKILL 10m mpirun -np 4 -bind-to core -mca pml ob1 -mca btl self,sm /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
Time per iteration on each process (ms)
Time 	 Compute time 	 Comm time
./jenkins_scripts/jenkins/ompi/ompi_jenkins.sh: line 144: 11851 Killed                  $timeout_exe mpirun -np $np $mca -mca pml ob1 -mca btl self,sm ${exe_path} ${exe_args}
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/107/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/107/tap-master-files/cov_stat.tap].
TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_107/output/errors/index.html
Setting commit status on GitHub for https://api.github.com/repos/mellanox-hpc/ompi-release/commit/3c798d0f363a5fcf6b07feec02df5788b972a3eb
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 9d8e92fc213f557026b86ab2ab9b2371931c1a1a to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/107/ and message: Merged build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1418 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_111/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/111/

**Build Log**
*last 50 lines*

 ```
[...truncated 141956 lines...]
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o overlap.o overlap.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o overlap overlap.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o no_overlap.o no_overlap.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o no_overlap no_overlap.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred.o conc_allred.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o conc_allred conc_allred.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred_th.o conc_allred_th.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o conc_allred_th conc_allred_th.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o collcomp.o collcomp.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o collcomp collcomp.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate.o message_rate.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o message_rate message_rate.o
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate_th.o message_rate_th.c
/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o message_rate_th message_rate_th.o
+ popd
/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace
+ '[' no == no ']'
+ btl_tcp=no
+ btl_vader=no
+ btl_openib=no
+ for exe in overlap latency
+ exe_path=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ PATH=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin:/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ LD_LIBRARY_PATH=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/lib:
+ mpi_runner 4 /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
+ local np=4
+ local exe_path=/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ local exe_args=8
+ local 'common_mca=-bind-to core'
+ local 'mca=-bind-to core'
+ '[' no == yes ']'
+ '[' yes == yes ']'
+ timeout -s SIGKILL 10m mpirun -np 4 -bind-to core -mca pml ob1 -mca btl self,sm /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
Time per iteration on each process (ms)
Time 	 Compute time 	 Comm time
./jenkins_scripts/jenkins/ompi/ompi_jenkins.sh: line 144: 15875 Killed                  $timeout_exe mpirun -np $np $mca -mca pml ob1 -mca btl self,sm ${exe_path} ${exe_args}
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/111/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/111/tap-master-files/cov_stat.tap].
TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_111/output/errors/index.html
Setting commit status on GitHub for https://api.github.com/repos/mellanox-hpc/ompi-release/commit/5a22f9c034b64468fe2e20e6d7ba4193eadd86c0
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 9d8e92fc213f557026b86ab2ab9b2371931c1a1a to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/111/ and message: Merged build finished.
```

Test FAILed.

**Comment by bureddy** [comment]
Its  race condition with thread multiple.  do not have fix for this yet

**Comment by bureddy** [comment]
There are two issues here in supporting MPI_THREAD_MULTIPLE
   1) need to enable ocoms thread multiple ( --enable-ocoms-multi-threads)
    2) need to enable thread support from hcoll ( ocoms_set_using_threads(false) ==> ocoms_set_using_threads(true)

But, enabling them by default might have some -ve impact on performance.

**Comment by mellanox-github** [comment]
* Coverity found 1418 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_113/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/113/
Test PASSed.

**Comment by bureddy** [comment]
Should we port these into ompi/ompi-release?

**Comment by miked-mellanox** [comment]
yes, thanks

**Pull request merged**
