### PR TITLE
oshmem: restore value of ompi_proc_local_proc before mpi finalize.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@miked-mellanox @igor-ivanov @alex-mikheev

**Comment by miked-mellanox** [comment]
jenkins:nohelp_txt bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//164/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//165/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/164/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/165/ for details. (Mellanox internal link)

**Pull request merged**
