### PR TITLE
sync with upstream

### PR DESCRIPTION
**Pull request by miked-mellanox**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1414 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_116/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
* Coverity found 1414 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_117/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/116/

**Build Log**
*last 50 lines*

 ```
[...truncated 142629 lines...]
+ btl_vader=yes
+ for mpit in '$abs_path/*.c'
++ basename .c
+ out_name=.c
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/.c /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/env_mpi.c
+ for mpit in '$abs_path/*.c'
++ basename .c
+ out_name=.c
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/.c /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test.c
++ echo /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ echo 'check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1'
check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_env_list
++ wc -l
+ val=2
+ '[' 2 -gt 0 ']'
+ echo 'test mca_base_env_list option in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1'
test mca_base_env_list option in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1
+ export XXX_C=3 XXX_D=4 XXX_E=5
+ XXX_C=3
+ XXX_D=4
+ XXX_E=5
++ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpirun -np 2 -mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' env
++ grep '^XXX_'
++ wc -l
+ val=10
+ '[' 10 -ne 10 ']'
+ echo 'mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E'
++ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpirun -np 2 -am /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/test_amca.conf /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/env_mpi
++ grep '^XXX_'
++ wc -l
+ val=0
+ '[' 0 -ne 10 ']'
+ exit 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/116/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/116/tap-master-files/cov_stat.tap].
TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_116/output/errors/index.html
Setting commit status on GitHub for https://github.com/mellanox-hpc/ompi-release/commit/6bdf5299eeb4a67c201c869a33cd9ddb1935c79c
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 7d9d6f75da9cf6ce74c2e7d499120a5a528c6c3e to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/116/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/117/

**Build Log**
*last 50 lines*

 ```
[...truncated 142629 lines...]
+ btl_vader=yes
+ for mpit in '$abs_path/*.c'
++ basename .c
+ out_name=.c
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/jenkins_scripts/jenkins/ompi/.c /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/jenkins_scripts/jenkins/ompi/env_mpi.c
+ for mpit in '$abs_path/*.c'
++ basename .c
+ out_name=.c
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/jenkins_scripts/jenkins/ompi/.c /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/jenkins_scripts/jenkins/ompi/mindist_test.c
++ echo /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ echo 'check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1'
check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1
++ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_env_list
++ wc -l
+ val=2
+ '[' 2 -gt 0 ']'
+ echo 'test mca_base_env_list option in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1'
test mca_base_env_list option in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1
+ export XXX_C=3 XXX_D=4 XXX_E=5
+ XXX_C=3
+ XXX_D=4
+ XXX_E=5
++ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpirun -np 2 -mca mca_base_env_list 'XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E' env
++ grep '^XXX_'
++ wc -l
+ val=10
+ '[' 10 -ne 10 ']'
+ echo 'mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E'
++ grep '^XXX_'
++ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/ompi_install1/bin/mpirun -np 2 -am /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/test_amca.conf /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace-2/jenkins_scripts/jenkins/ompi/env_mpi
++ wc -l
+ val=0
+ '[' 0 -ne 10 ']'
+ exit 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/117/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/117/tap-master-files/cov_stat.tap].
TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_117/output/errors/index.html
Setting commit status on GitHub for https://github.com/mellanox-hpc/ompi-release/commit/6bdf5299eeb4a67c201c869a33cd9ddb1935c79c
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 00c0400d15230c90cbf381ec18c035e356a24eda to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/117/ and message: Merged build finished.
```

Test FAILed.

**Comment by elenash** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1414 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_118/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/118/
Test PASSed.

**Pull request merged**
