### PR TITLE
sync with upstream

### PR DESCRIPTION
**Pull request by miked-mellanox**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1412 errors for all
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//146/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Di0gen** [comment]
test this please

**Comment by Di0gen** [comment]
test this please

**Comment by Di0gen** [comment]
retest this please

**Comment by Di0gen** [comment]
retest this please

**Comment by Di0gen** [comment]
retest this please

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1412 errors for all
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//147/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
