### PR TITLE
Pr/error output

### PR DESCRIPTION
**Pull request by igor-ivanov**
@yosefe @alex-mikheev @miked-mellanox could you review

### CODE REVIEW

**Comment by yosefe** [comment]
@igor-ivanov You are modifying a local variable which has no side effect. So output open will be done every time this function is called.

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//168/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/168/ for details. (Mellanox internal link)

**Comment by igor-ivanov** [comment]
@yosefe You are right.
I see following ways:
1. current
2. passing &output_id
3. open (oshmem_atomic_base_framework.output) for every mca framework

My preferable way is the 3th.

**Comment by yosefe** [comment]
@igor-ivanov i also think 3 is best. we need it just for atomic, spml, memheap for starters, right?

**Comment by igor-ivanov** [comment]
@yosefe mca/sshmem and in addition SHMEM_API_VERBOSE(shmem_api_logger_output) should be changed too.
I can do 2 point if there is no objections.

**Comment by miked-mellanox** [comment]
sounds good. lets do it.

**Comment by igor-ivanov** [comment]
@yosefe @alex-mikheev @miked-mellanox see update

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//170/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//171/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/170/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/171/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//172/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/172/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
:+1: 
please submit PRs for master/v2.x/1.10.2

**Pull request merged**
