### PR TITLE
Merge from topic/tune_patch branch

### PR DESCRIPTION
**Pull request by elenash**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1418 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_95/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/95/

**Build Log**
*last 50 lines*

 ```
[...truncated 143404 lines...]
++ wc -l
+ val=2
+ '[' 2 -gt 0 ']'
+ echo 'test the dist mapping policy in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1'
test the dist mapping policy in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1
++ dirname ./jenkins_scripts/jenkins/ompi/ompi_jenkins.sh
+ rel_path=./jenkins_scripts/jenkins/ompi
++ readlink -f ./jenkins_scripts/jenkins/ompi
+ abs_path=/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test.c
++ ibstat -l
+ for hca_dev in '$(ibstat -l)'
+ set +e
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpirun -np 8 --map-by dist -mca rmaps_dist_device mlx4_0 /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test
--------------------------------------------------------------------------
The specified mapping policy is not recognized:

  Policy: dist

Please check for a typo or ensure that the option is a supported
one.
--------------------------------------------------------------------------
+ val=213
+ set -e
+ '[' 213 -ne 0 ']'
++ grep Skip
++ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpirun -np 8 --map-by dist -mca rmaps_dist_device mlx4_0 /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ '[' mellanox-v1.8 == mellanox-v1.8 ']'
+ exit 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/95/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/95/tap-master-files/cov_stat.tap].
TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_95/output/errors/index.html
Setting commit status on GitHub for https://api.github.com/repos/mellanox-hpc/ompi-release/commit/7c82df12466364a8d2e67b7225f309747a68d2a0
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Request made to compress build log
Sending email to: hpc_tests@mellanox.com bg@itseez.com
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 1ea4859038fa2381bb34e834b6ebad0bd5634871 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/95/ and message: Merged build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1418 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_96/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/96/

**Build Log**
*last 50 lines*

 ```
[...truncated 143400 lines...]
++ wc -l
+ val=2
+ '[' 2 -gt 0 ']'
+ echo 'test the dist mapping policy in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1'
test the dist mapping policy in /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1
++ dirname ./jenkins_scripts/jenkins/ompi/ompi_jenkins.sh
+ rel_path=./jenkins_scripts/jenkins/ompi
++ readlink -f ./jenkins_scripts/jenkins/ompi
+ abs_path=/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test.c
++ ibstat -l
+ for hca_dev in '$(ibstat -l)'
+ set +e
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpirun -np 8 --map-by dist -mca rmaps_dist_device mlx4_0 /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test
--------------------------------------------------------------------------
The specified mapping policy is not recognized:

  Policy: dist

Please check for a typo or ensure that the option is a supported
one.
--------------------------------------------------------------------------
+ val=213
+ set -e
+ '[' 213 -ne 0 ']'
++ grep Skip
++ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpirun -np 8 --map-by dist -mca rmaps_dist_device mlx4_0 /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ '[' mellanox-v1.8 == mellanox-v1.8 ']'
+ exit 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/96/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/96/tap-master-files/cov_stat.tap].
TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_96/output/errors/index.html
Setting commit status on GitHub for https://api.github.com/repos/mellanox-hpc/ompi-release/commit/7c82df12466364a8d2e67b7225f309747a68d2a0
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Request made to compress build log
Sending email to: hpc_tests@mellanox.com bg@itseez.com
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 1ea4859038fa2381bb34e834b6ebad0bd5634871 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/96/ and message: Merged build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1419 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_98/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/98/

**Build Log**
*last 50 lines*

 ```
[...truncated 43914 lines...]
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi/contrib/vt'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
 (cd vt && make -j4 top_distdir=../../../../openmpi-1.8.4 distdir=../../../../openmpi-1.8.4/ompi/contrib/vt/vt \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi/contrib/vt/vt'
make[4]: warning: -jN forced in submake: disabling jobserver mode.
:
test -d "../../../../openmpi-1.8.4/ompi/contrib/vt/vt" || mkdir "../../../../openmpi-1.8.4/ompi/contrib/vt/vt"
 (cd extlib && make -j4 top_distdir=../../../../../openmpi-1.8.4 distdir=../../../../../openmpi-1.8.4/ompi/contrib/vt/vt/extlib \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[5]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi/contrib/vt/vt/extlib'
make[5]: warning: -jN forced in submake: disabling jobserver mode.
 (cd otf && make -j4 top_distdir=../../../../../../openmpi-1.8.4 distdir=../../../../../../openmpi-1.8.4/ompi/contrib/vt/vt/extlib/otf \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[6]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi/contrib/vt/vt/extlib/otf'
make[6]: warning: -jN forced in submake: disabling jobserver mode.
make[6]: *** No rule to make target `config/compile', needed by `distdir'.  Stop.
make[6]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi/contrib/vt/vt/extlib/otf'
make[5]: *** [distdir] Error 1
make[5]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi/contrib/vt/vt/extlib'
make[4]: *** [distdir] Error 1
make[4]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi/contrib/vt/vt'
make[3]: *** [distdir] Error 1
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi/contrib/vt'
make[2]: *** [distdir] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi'
make[1]: *** [distdir] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace'
make: *** [dist] Error 2
Make distcheck failed.  Aborting
+ exit 11
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/98/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/98/tap-master-files/cov_stat.tap].
TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_98/output/errors/index.html
Setting commit status on GitHub for https://api.github.com/repos/mellanox-hpc/ompi-release/commit/f6a18ddfb4928d91e961bd21d3d0958c12be5558
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Request made to compress build log
Sending email to: hpc_tests@mellanox.com bg@itseez.com
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 1ea4859038fa2381bb34e834b6ebad0bd5634871 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/98/ and message: Merged build finished.
```

Test FAILed.

**Comment by elenash** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1419 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_99/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/99/
Test PASSed.

**Pull request merged**
