### PR TITLE
oshmem: Modify proc component

### PR DESCRIPTION
**Pull request by igor-ivanov**
@miked-mellanox @yosefe could you review

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//162/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/162/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
test:nohelp_txt
bot:retest

**Comment by miked-mellanox** [comment]
jenkins:nohelp_txt bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//163/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/163/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
@igor-ivanov - could you please PR it into v1.10 tree. thanks

**Pull request closed without merging**
