### PR TITLE
Fix coverity issues

### PR DESCRIPTION
**Pull request by igor-ivanov**
This pull request fixes coverity issues in following places as
ompi/mca/coll/fca/ and oshmem/ source code were touched.

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1457 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_80/output/errors/index.html

* Coverity found 8 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/oshmem_80/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/80/
Test PASSed.

**Comment by igor-ivanov** [comment]
@alex-mikheev could you please look at this?

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1451 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_81/output/errors/index.html

* Coverity found 2 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/oshmem_81/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/81/
Test PASSed.

**Comment by igor-ivanov** [comment]
commit was amended with notices

**Comment by mellanox-github** [comment]
* Coverity found 1460 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_82/output/errors/index.html

* Coverity found 12 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/oshmem_82/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by miked-mellanox** [comment]
can we have 0 cov shmem errors. thx

**Comment by igor-ivanov** [comment]
removing null pointer check forces coverity issues as
```
(7) Event var_deref_model:	Passing null pointer "rcv_buffer" to "opal_free", which dereferences it. (The dereference is assumed on the basis of the 'nonnull' parameter attribute.)
Also see events:	[assign_zero]
698  	    free(rcv_buffer);
```
do we need to fix coverity issues in ptmalloc code too?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/82/
Test PASSed.

**Comment by igor-ivanov** [comment]
commit was amended with additional ommit message and opal_free fix

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1434 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_83/output/errors/index.html

* Coverity found 2 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/oshmem_83/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/83/
Test PASSed.

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1432 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_85/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
* Coverity found 1432 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_84/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/84/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/85/
Test PASSed.

**Pull request merged**
