### PR TITLE
openib: added a new vendor_part_id for Mellanox ConnectX4-LX.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1412 errors for all
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//145/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-mellanox-v1.8-PR/145/

**Comment by alinask** [comment]
@miked-mellanox Can you please review?

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
