### PR TITLE
OSHMEM/SPML/ikrit: cleanup

### PR DESCRIPTION
**Pull request by alex-mikheev**
@yosefe @miked-mellanox please take a look

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//167/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/167/ for details. (Mellanox internal link)

**Comment by yosefe** [comment]
what about the `if` which checks both ud_only and hw_channel? can this be changed to check just ud_only?

**Comment by mellanox-github** [comment]
* Coverity found 1442 errors for all
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR//169/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/169/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
@yosefe , @alex-mikheev - please submit appropriate PRs for master/v2.x and v1.10
thanks

**Pull request merged**
