### PR TITLE
sync with upstream

### PR DESCRIPTION
**Pull request by miked-mellanox**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1411 errors for all
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//137/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/137/

**Build Log**
*last 50 lines*

 ```
[...truncated 55553 lines...]

Success rank - 6: only one NUMA is scheduled.

Success rank - 5: only one NUMA is scheduled.

Success rank - 0: only one NUMA is scheduled.
+ val=0
+ '[' 0 -ne 0 ']'
+ for hca_dev in '$(ibstat -l)'
++ cat /sys/class/infiniband/mlx5_0/device/numa_node
+ var=0
+ export TEST_CLOSEST_NUMA=0
+ TEST_CLOSEST_NUMA=0
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpirun -np 8 -mca mpi_warn_on_fork 0 -mca btl_openib_warn_default_gid_prefix 0 --map-by dist -mca rmaps_dist_device mlx5_0 -x TEST_CLOSEST_NUMA -x TEST_PHYS_ID_COUNT -x TEST_CORE_ID_COUNT /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test

Success rank - 0: only one NUMA is scheduled.

Success rank - 7: only one NUMA is scheduled.

Success rank - 1: only one NUMA is scheduled.

Success rank - 3: only one NUMA is scheduled.

Success rank - 6: only one NUMA is scheduled.

Success rank - 2: only one NUMA is scheduled.

Success rank - 5: only one NUMA is scheduled.

Success rank - 4: only one NUMA is scheduled.
+ val=0
+ '[' 0 -ne 0 ']'
+ set -e
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/137/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/137/tap-master-files/cov_stat.tap].
There are failed test cases and the job is configured to mark the build as failure. Marking build as FAILURE
TAP Reports Processing: FINISH
Build step 'Publish TAP Results' changed build result to FAILURE
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/cov_build to /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/137/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/mellanox-hpc/ompi-release/commit/f71949bdb7f336646861b15f2590d8b9921e7efd
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] TAP test failed
[BFA] Done. 0s
Setting status of 13b46b75a2692e693cdee64a05d407c8f5215fa8 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/137/ and message: Build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1411 errors for all
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//138/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/138/

**Build Log**
*last 50 lines*

 ```
[...truncated 55552 lines...]
Success rank - 1: only one NUMA is scheduled.

Success rank - 2: only one NUMA is scheduled.

Success rank - 0: only one NUMA is scheduled.

Success rank - 6: only one NUMA is scheduled.
+ val=0
+ '[' 0 -ne 0 ']'
+ for hca_dev in '$(ibstat -l)'
++ cat /sys/class/infiniband/mlx5_0/device/numa_node
+ var=0
+ export TEST_CLOSEST_NUMA=0
+ TEST_CLOSEST_NUMA=0
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpirun -np 8 -mca mpi_warn_on_fork 0 -mca btl_openib_warn_default_gid_prefix 0 --map-by dist -mca rmaps_dist_device mlx5_0 -x TEST_CLOSEST_NUMA -x TEST_PHYS_ID_COUNT -x TEST_CORE_ID_COUNT /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test

Success rank - 7: only one NUMA is scheduled.

Success rank - 4: only one NUMA is scheduled.

Success rank - 1: only one NUMA is scheduled.

Success rank - 2: only one NUMA is scheduled.

Success rank - 0: only one NUMA is scheduled.

Success rank - 3: only one NUMA is scheduled.

Success rank - 5: only one NUMA is scheduled.

Success rank - 6: only one NUMA is scheduled.
+ val=0
+ '[' 0 -ne 0 ']'
+ set -e
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/138/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/138/tap-master-files/cov_stat.tap].
There are failed test cases. Marking build as UNSTABLE
TAP Reports Processing: FINISH
Build step 'Publish TAP Results' changed build result to UNSTABLE
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/cov_build to /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/138/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/mellanox-hpc/ompi-release/commit/f71949bdb7f336646861b15f2590d8b9921e7efd
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 13b46b75a2692e693cdee64a05d407c8f5215fa8 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/138/ and message: Build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1411 errors for all
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//139/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/139/

**Build Log**
*last 50 lines*

 ```
[...truncated 55541 lines...]
Success rank - 6: only one NUMA is scheduled.

Success rank - 2: only one NUMA is scheduled.

Success rank - 0: only one NUMA is scheduled.

Success rank - 3: only one NUMA is scheduled.
+ val=0
+ '[' 0 -ne 0 ']'
+ for hca_dev in '$(ibstat -l)'
++ cat /sys/class/infiniband/mlx5_0/device/numa_node
+ var=0
+ export TEST_CLOSEST_NUMA=0
+ TEST_CLOSEST_NUMA=0
+ /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/ompi_install1/bin/mpirun -np 8 --map-by dist -mca rmaps_dist_device mlx5_0 -x TEST_CLOSEST_NUMA -x TEST_PHYS_ID_COUNT -x TEST_CORE_ID_COUNT /scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_scripts/jenkins/ompi/mindist_test

Success rank - 6: only one NUMA is scheduled.

Success rank - 1: only one NUMA is scheduled.

Success rank - 5: only one NUMA is scheduled.

Success rank - 3: only one NUMA is scheduled.

Success rank - 4: only one NUMA is scheduled.

Success rank - 2: only one NUMA is scheduled.

Success rank - 7: only one NUMA is scheduled.

Success rank - 0: only one NUMA is scheduled.
+ val=0
+ '[' 0 -ne 0 ']'
+ set -e
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/139/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/139/tap-master-files/cov_stat.tap].
There are failed test cases. Marking build as UNSTABLE
TAP Reports Processing: FINISH
Build step 'Publish TAP Results' changed build result to UNSTABLE
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/cov_build to /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/139/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/mellanox-hpc/ompi-release/commit/f71949bdb7f336646861b15f2590d8b9921e7efd
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 13b46b75a2692e693cdee64a05d407c8f5215fa8 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/139/ and message: Build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1411 errors for all
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//140/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/140/
Test PASSed.

**Pull request merged**
