### PR TITLE
sync with upstream

### PR DESCRIPTION
**Pull request by miked-mellanox**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1413 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_122/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/122/
Test PASSed.

**Comment by bureddy** [comment]
bot:reset

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/127/

**Build Log**
*last 50 lines*

 ```
[...truncated 24 lines...]
 > /usr/bin/git rev-parse refs/remotes/origin/origin/pr/83/merge^{commit} # timeout=60
 > /usr/bin/git rev-parse origin/pr/83/merge^{commit} # timeout=60
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/jenkins_sidelinks.txt (No such file or directory)
Setting commit status on GitHub for https://github.com/mellanox-hpc/ompi-release/commit/d99a340c5b7741cae0af85379b9304bc791d0e9b
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: {"message":"No commit found for SHA: d99a340c5b7741cae0af85379b9304bc791d0e9b","documentation_url":"https://developer.github.com/v3/repos/statuses/"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:496)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:780)
	at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:127)
	at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:764)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:724)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1769)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/mellanox-hpc/ompi-release/statuses/d99a340c5b7741cae0af85379b9304bc791d0e9b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1673)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1671)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1244)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/mellanox-hpc/ompi-release/statuses/d99a340c5b7741cae0af85379b9304bc791d0e9b
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of ca638dc88c270e3f8bb10514278f98eb316cd6db to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/127/ and message: Build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Pull request merged**
