### PR TITLE
MTL_MXM/PML_YALLA: fix coverity issues.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1488 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_74/output/errors/index.html

* Coverity found 30 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/oshmem_74/output/errors/index.html

* Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/fca_74/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/74/
Test PASSed.

**Comment by alinask** [comment]
@yosefe can you please review?

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
