### PR TITLE
sync with ompi

### PR DESCRIPTION
**Pull request by miked-mellanox**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found $nerrors errors for ${cov_proj_disp}: $cov_url


* Coverity found $nerrors errors for ${cov_proj_disp}: $cov_url


* Coverity found $nerrors errors for ${cov_proj_disp}: $cov_url <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/61/

**Build Log**
*last 50 lines*

 ```
[...truncated 65181 lines...]
test . = "../../../../../../orte/mca/errmgr/default_tool" || test -z "" || rm -f 
rm -f ./so_locations
rm -rf ./.deps
rm -f Makefile
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/openmpi-1.8.4/_build/sub/orte/mca/errmgr/default_tool'
Making distclean in mca/errmgr/default_hnp
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/openmpi-1.8.4/_build/sub/orte/mca/errmgr/default_hnp'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
test -z "*~ .#*" || rm -f *~ .#*
rm -rf .libs _libs
test -z "mca_errmgr_default_hnp.la" || rm -f mca_errmgr_default_hnp.la
test -z "" || rm -f 
rm -f *.o
rm -f *.lo
rm -f *.tab.c
test -z "" || rm -f 
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
test . = "../../../../../../orte/mca/errmgr/default_hnp" || test -z "" || rm -f 
rm -f ./so_locations
rm -rf ./.deps
rm -f Makefile
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/openmpi-1.8.4/_build/sub/orte/mca/errmgr/default_hnp'
Making distclean in mca/errmgr/default_orted
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-mellanox-v1.8-PR/workspace/openmpi-1.8.4/_build/sub/orte/mca/errmgr/default_orted'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
test -z "*~ .#*" || rm -f *~ .#*
rm -rf .libs _libs
test -z "mca_errmgr_default_orted.la" || rm -f mca_errmgr_default_orted.la
test -z "" || rm -f 
Build timed out (after 50 minutes). Marking the build as failed.
rm -f *.o
Build was aborted
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/61/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-mellanox-v1.8-PR/builds/61/tap-master-files/cov_stat.tap].
TAP Reports Processing: FINISH
coverity_for_all	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_61/c/output/errors/index.html
coverity_for_oshmem	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/oshmem_61/c/output/errors/index.html
coverity_for_fca	http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/fca_61/c/output/errors/index.html
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Request made to compress build log
Sending email to: hpc_tests@mellanox.com bg@itseez.com
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of a0725e739b0af0252bb11576d13aee9987885731 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR/61/ and message: Merged build finished.
```

Test FAILed.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 859 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_62/c/output/errors/index.html

* Coverity found 41 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/oshmem_62/c/output/errors/index.html

* Coverity found 6 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/fca_62/c/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/62/
Test PASSed.

**Pull request merged**
