### PR TITLE
Merge from mellanox-v1.8 internal branch

### PR DESCRIPTION
**Pull request by elenash**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 37 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_68/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by elenash** [comment]
No. There are some small mistakes, fixed them:
export XXX_C=3 XXX_D=4 XXX_E=5   
         # check amca param
            echo "mca_base_env_list=XXX_A=1;XXX_B=2;XXX_C;XXX_D;XXX_E" > $WORKSPACE/test_amca.conf
            val=$($OMPI_HOME/bin/mpirun -np 2 -am $WORKSPACE/test_amca.conf env|grep ^XXX_|wc -l)
            if [ $val -ne 10 ]; then
                exit 1
            fi

But If app doesn't call MPI_Init, -am doesn't work. So need to add a simple executable which call for getenv and use it instead of "env".

**Comment by elenash** [comment]
I'll clarify first why -am doesn't work without mpi_init

**Comment by miked-mellanox** [comment]
thanks, plz fix in the jenkins repo.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/68/
Test PASSed.

**Comment by elenash** [comment]
Test must be working for mellanox-v1.8. The issue is in trunk only.

**Comment by miked-mellanox** [comment]
retest this please

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 37 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-mellanox-v1.8-PR//ws/cov_build/all_69/output/errors/index.html <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-mellanox-v1.8-PR/69/
Test PASSed.

**Comment by miked-mellanox** [comment]
@elenash - do we need to PR it into v1.8? or v1.8 does not support this mca var but trunk only?

**Comment by elenash** [comment]
@miked-mellanox 1.8 doesn't support this feature, so PR is not needed.

**Pull request merged**
